version: 2
updates:
  # Enable version updates for GitHub Actions
  # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      # Group all GitHub Actions updates into a single PR
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
      include: scope
